[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Give it more flash/RAM partitions since camera streaming uses a lot of memory
board_build.partitions = huge_app.csv

; Enable PSRAM support (Crucial for ESP32-CAM to allocate large frames)
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Need the ESP32 Camera library
lib_deps =
    esp32-camera